---
config0:
  resQuantity : 5 5 5
  resource0:
    left: A B C 0
    right: A B C 0
    up: A B C 0
    down: A B C 0
  resource1:
    left: A B C 0
    right: A B C 0
    up: A B C 0
    down: A B C 0
  resource2:
    left: A B C 0
    right: A B C 0
    up: A B C 0
    down: A B C 0
config1:
  resQuantity : 5 5 5
  resource0:
    left: A 0
    right: A 0
    up: A C 0
    down: A B 0
  resource1:
    left: A 0
    right: A 0
    up: A 0
    down: A 0
  resource2:
    left: A 0
    right: A 0
    up: A 0
    down: A 0
config2:
  resQuantity : 5 5 5
  resource0:
    left: B 0
    right: B 0
    up: B 0
    down: B 0
  resource1:
    left: A C 0
    right: A C 0
    up: A C 0
    down: A C 0
  resource2:
    left: B 0
    right: B 0
    up: B 0
    down: B 0
config3:
  resQuantity : 5 5 5
  resource0:
    left: A B 0
    right: A B 0
    up: A B 0
    down: A B 0
  resource1:
    left: A 0
    right: A 0
    up: A 0
    down: A 0
  resource2:
    left: A C 0
    right: A C 0
    up: A C 0
    down: A C 0
config4:
  resQuantity : 5 5 5
  resource0:
    left: A C 0
    right: A C 0
    up: A C 0
    down: A B 0
  resource1:
    left: B C 0
    right: A B 0
    up: A B 0
    down: B C 0
  resource2:
    left: A 0
    right: B 0
    up: B 0
    down: A 0
config5:
  resQuantity : 5 5 5
  resource0:
    left: B 0
    right: B 0
    up: B 0
    down: B 0
  resource1:
    left: A 0
    right: A 0
    up: A 0
    down: A 0
  resource2:
    left: 0
    right: 0
    up: 0
    down: 0
config6:
  resQuantity : 5 5 5
  resource0:
    left: 0
    right: 0
    up: 0
    down: 0
  resource1:
    left: B 0
    right: B 0
    up: B 0
    down: B 0
  resource2:
    left: 0
    right: 0
    up: 0
    down: 0
config7:
  resQuantity : 5 5 5
  resource0:
    left: A C 0
    right: A C 0
    up: A B 0
    down: A C 0
  resource1:
    left: 0
    right: 0
    up: C 0
    down: A 0
  resource2:
    left: A 0
    right: A 0
    up: A 0 
    down: B 0
config8:
  resQuantity : 5 5 5
  resource0:
    left: C 0
    right: C 0
    up: C 0
    down: C 0
  resource1:
    left: 0
    right: 0
    up: 0
    down: 0
  resource2:
    left: A C 0
    right: A C 0
    up: A C 0 
    down: A C 0