---
config0:
  resQuantity : 5 5 5
  resource0:
    left: A B C
    right: A B C
    up: A B C
    down: A B C
  resource1:
    left: A B C
    right: A B C
    up: A B C
    down: A B C
  resource2:
    left: A B C
    right: A B C
    up: A B C
    down: A B C
config1:
  resQuantity : 5 5 5
  resource0:
    left: A
    right: A
    up: A C
    down: A B
  resource1:
    left: A
    right: A
    up: A
    down: A
  resource2:
    left: A
    right: A
    up: A
    down: A
config2:
  resQuantity : 5 5 5
  resource0:
    left: B
    right: B
    up: B
    down: B
  resource1:
    left: A C
    right: A C
    up: A C
    down: A C
  resource2:
    left: B
    right: B
    up: B
    down: B
config3:
  resQuantity : 5 5 5
  resource0:
    left: A B
    right: A B
    up: A B
    down: A B
  resource1:
    left: A
    right: A
    up: A
    down: A
  resource2:
    left: A C
    right: A C
    up: A C
    down: A C
config4:
  resQuantity : 5 5 5
  resource0:
    left: A C
    right: A C
    up: A C
    down: A B
  resource1:
    left: B C
    right: A B
    up: A B
    down: B C
  resource2:
    left: A
    right: B
    up: B
    down: A
config5:
  resQuantity : 5 5 5
  resource0:
    left: B
    right: B
    up: B
    down: B
  resource1:
    left: A
    right: A
    up: A
    down: A
  resource2:
    left:
    right:
    up:
    down:
config6:
  resQuantity : 5 5 5
  resource0:
    left:
    right:
    up:
    down:
  resource1:
    left: B
    right: B
    up: B
    down: B
  resource2:
    left:
    right:
    up:
    down:
config7:
  resQuantity : 5 5 5
  resource0:
    left: A C
    right: A C
    up: A B
    down: A C
  resource1:
    left:
    right:
    up: C
    down: A
  resource2:
    left: A
    right: A
    up: A
    down: B
config8:
  resQuantity : 5 5 5
  resource0:
    left: C
    right: C
    up: C
    down: C
  resource1:
    left:
    right:
    up:
    down:
  resource2:
    left: A C
    right: A C
    up: A C
    down: A C